version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/ibm-web-app.war ibm-web-app.war
artifacts:
  files:
    - ibm-web-app.war
    - .ebextensions/**/*
